// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SinamaApp.DataAccessLayer.Concrete.EFCore;

#nullable disable

namespace SinamaApp.DataAccessLayer.Migrations
{
    [DbContext(typeof(SinamaAppDbContext))]
    [Migration("20260417172128_mig4")]
    partial class mig4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FilmOyuncu", b =>
                {
                    b.Property<int>("FilmlerID")
                        .HasColumnType("int");

                    b.Property<int>("OyuncularID")
                        .HasColumnType("int");

                    b.HasKey("FilmlerID", "OyuncularID");

                    b.HasIndex("OyuncularID");

                    b.ToTable("FilmOyuncu");
                });

            modelBuilder.Entity("SinamaApp.Entities.Concrete.Bilet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BiletDurumu")
                        .HasColumnType("int");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KoltukID")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SatinAlmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SeansID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KoltukID");

                    b.HasIndex("KullaniciID");

                    b.HasIndex("SeansID", "KoltukID")
                        .IsUnique();

                    b.ToTable("Biletler");
                });

            modelBuilder.Entity("SinamaApp.Entities.Concrete.Film", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BasRolOyuncuID")
                        .HasColumnType("int");

                    b.Property<string>("FilmAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FilmYili")
                        .HasColumnType("int");

                    b.Property<int>("KategoriID")
                        .HasColumnType("int");

                    b.Property<int>("YonetmenID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BasRolOyuncuID");

                    b.HasIndex("KategoriID");

                    b.HasIndex("YonetmenID");

                    b.ToTable("Filmler");
                });

            modelBuilder.Entity("SinamaApp.Entities.Concrete.Kategori", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("SinamaApp.Entities.Concrete.Koltuk", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Numara")
                        .HasColumnType("int");

                    b.Property<int>("SalonID")
                        .HasColumnType("int");

                    b.Property<string>("Satir")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("SalonID");

                    b.HasIndex("Numara", "Satir", "SalonID")
                        .IsUnique();

                    b.ToTable("Koltuk");
                });

            modelBuilder.Entity("SinamaApp.Entities.Concrete.Kullanici", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("SinamaApp.Entities.Concrete.Oyuncu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Oyuncular");
                });

            modelBuilder.Entity("SinamaApp.Entities.Concrete.Salon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("SalonNo")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SalonNo")
                        .IsUnique();

                    b.ToTable("Salonlar");
                });

            modelBuilder.Entity("SinamaApp.Entities.Concrete.Seans", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("FilmID")
                        .HasColumnType("int");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalonID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SeansSaati")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("FilmID");

                    b.HasIndex("SalonID");

                    b.ToTable("Seanslar");
                });

            modelBuilder.Entity("SinamaApp.Entities.Concrete.Yonetmen", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Yonetmenler");
                });

            modelBuilder.Entity("FilmOyuncu", b =>
                {
                    b.HasOne("SinamaApp.Entities.Concrete.Film", null)
                        .WithMany()
                        .HasForeignKey("FilmlerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SinamaApp.Entities.Concrete.Oyuncu", null)
                        .WithMany()
                        .HasForeignKey("OyuncularID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SinamaApp.Entities.Concrete.Bilet", b =>
                {
                    b.HasOne("SinamaApp.Entities.Concrete.Koltuk", "Koltuk")
                        .WithMany()
                        .HasForeignKey("KoltukID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SinamaApp.Entities.Concrete.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SinamaApp.Entities.Concrete.Seans", "Seans")
                        .WithMany()
                        .HasForeignKey("SeansID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Koltuk");

                    b.Navigation("Kullanici");

                    b.Navigation("Seans");
                });

            modelBuilder.Entity("SinamaApp.Entities.Concrete.Film", b =>
                {
                    b.HasOne("SinamaApp.Entities.Concrete.Oyuncu", "BasRolOyuncu")
                        .WithMany()
                        .HasForeignKey("BasRolOyuncuID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SinamaApp.Entities.Concrete.Kategori", "Kategori")
                        .WithMany("Filmler")
                        .HasForeignKey("KategoriID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SinamaApp.Entities.Concrete.Yonetmen", "Yonetmen")
                        .WithMany("Filmler")
                        .HasForeignKey("YonetmenID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BasRolOyuncu");

                    b.Navigation("Kategori");

                    b.Navigation("Yonetmen");
                });

            modelBuilder.Entity("SinamaApp.Entities.Concrete.Koltuk", b =>
                {
                    b.HasOne("SinamaApp.Entities.Concrete.Salon", "Salon")
                        .WithMany("Koltuklar")
                        .HasForeignKey("SalonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("SinamaApp.Entities.Concrete.Seans", b =>
                {
                    b.HasOne("SinamaApp.Entities.Concrete.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SinamaApp.Entities.Concrete.Salon", "Salon")
                        .WithMany("Seanslar")
                        .HasForeignKey("SalonID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("SinamaApp.Entities.Concrete.Kategori", b =>
                {
                    b.Navigation("Filmler");
                });

            modelBuilder.Entity("SinamaApp.Entities.Concrete.Salon", b =>
                {
                    b.Navigation("Koltuklar");

                    b.Navigation("Seanslar");
                });

            modelBuilder.Entity("SinamaApp.Entities.Concrete.Yonetmen", b =>
                {
                    b.Navigation("Filmler");
                });
#pragma warning restore 612, 618
        }
    }
}
